server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
#          filters:
#            - AddRequestHeader=su, xiaosu
#            - AddRequestParameter=name, suhongrun
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id: su-fallback
#          uri: http://www.baidu.com
#          predicates:
#            - Path=/fallback
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
